### ISSUE TITLE
Text AA on and off on Android

### ISSUE THREAD

**Issue by yjbanov** [domokit/sky_engine#1169]
Text is not anti-aliased on Android, but not consistently. Going to home screen and then back to Sky Shell fixes it, but after a few interactions it's back to no AA:

![sky text rendering android](https://cloud.githubusercontent.com/assets/211513/9869609/3d86cdba-5b3a-11e5-8e90-d231eaa95cac.png)

Repro (almost straight from the `MyToolbar` from the tutorial):

```dart
class MyToolBar extends Component {
  Widget build() {
    return new Container(
      decoration: const BoxDecoration(
        backgroundColor: const Color(0xFF00FFFF)
      ),
      height: 56.0,
      padding: const EdgeDims.symmetric(horizontal: 8.0),
      child: new Row([
        new Flexible(child: new Text('My awesome toolbar')),
        new FlatButton(child: new Text('Search'))
      ])
    );
  }
}
```

**Comment by yjbanov** [comment]
Oh yeah, about version numbers:

  sky 0.0.43
  sky_engine 0.0.20
  sky_services 0.0.20
  sky_tools 0.0.10

Dart: 1.12.1 (Tue Sep  8 04:10:39 2015) on "macos_x64"

**Comment by abarth** [comment]
@yjbanov This bug is a bug in the compositor that's fixed on master.  I'll push a new release with the fix.

/cc @chinmaygarde

**Comment by chinmaygarde** [comment]
Yeah. This was fixed late last week. My bad.

**Comment by abarth** [comment]
Ok, new version published.  Please reopen this issue if the bug still happens with sky 0.0.44 / sky_engine 0.0.21.  Thanks for the report!

**Comment by yjbanov** [comment]
The issue is still there in `0.0.44`/`0.0.21`. Here's an excerpt from my `.packages` file:

```
sky:file:///Users/yjbanov/.pub-cache/hosted/pub.dartlang.org/sky-0.0.44/lib/
sky_engine:file:///Users/yjbanov/.pub-cache/hosted/pub.dartlang.org/sky_engine-0.0.21/lib/
sky_services:file:///Users/yjbanov/.pub-cache/hosted/pub.dartlang.org/sky_services-0.0.21/lib/
sky_tools:file:///Users/yjbanov/.pub-cache/hosted/pub.dartlang.org/sky_tools-0.0.10/lib/
```

**Comment by yjbanov** [comment]
(also, cannot reopen issues, only comment)

**Comment by chinmaygarde** [comment]
Taking a look at it now. Thanks

**Comment by yjbanov** [comment]
False alarm! `sky_tool listen` does not reupload `SkyShell.apk`. `sky_tool start` seems to have fixed it.

**Comment by chinmaygarde** [comment]
Cool :)
